name: main
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24.x'      # This step prints an output (time) from the previous step's action.
      - run: npm install

      - run: npm run build
      
      - name: Validate
        uses: ./
